### ISSUE TITLE
Is it possible to add a managed identity user? 

### ISSUE THREAD

**Issue by dsfrederic** [betr-io/terraform-provider-mssql#18]
Hello, 

I was wondering if it was possible to ad an Managed Identity using this terraform provider? 

This is the SQL script I would use to add the user
```
CREATE USER [your application name] FROM EXTERNAL PROVIDER;
ALTER ROLE [role name] ADD MEMBER [your application name];
```

**Comment by aman-subscriptions** [comment]
I was trying to do the same :( But keep getting this error:
unable to create user [master].[<identity-name>]: mssql: Cannot add the principal '<identity-name>', because it does not exist or you do not have permission.

**Comment by alexdresko** [comment]
@aman-subscriptions I was getting the "Cannot add the principal" error before I realized that I needed to use the `depends_on` thing inside `mssql_user` because `mssql_user` wasn't aware that my SQL database wasn't finished being created.
