### ISSUE TITLE
add azure cli auth

### ISSUE THREAD

**Issue by majidaldo** [betr-io/terraform-provider-mssql#20]
Azure cli authentication, `az login`,  is becoming a 'universal' way to log into azure.

**Comment by magne** [comment]
This plugin is not about manipulating Azure resources, for which `az login` is necessary, but rather about creating users and logins in SQL Server. Even when created in Azure, the SQL Server login is separate from the Azure login.

**Comment by majidaldo** [comment]
The request is technically about getting credentials to manage the server. .. Not about managing azure.
