### ISSUE TITLE
Empty azure_login client_id and client_secret results in "db connection failed after 30s timeout"

### ISSUE THREAD

**Issue by teplyuska** [betr-io/terraform-provider-mssql#25]
While developing pipelines to run terraform, a state file was accidentally saved with empty client_id and client_secret in azure_login.

When running "terraform plan" the refresh would result in "db connection failed after 30s timeout"

It might be helpful to others if this scenario resulted in another error message.

version 0.2.4

**Comment by ramondeklein** [comment]
I have the same issue. I checked and I can access the database from this IP address, but it doesn't seem to be able to process these resources anymore :-(

**Comment by gperezivo** [comment]
> I have the same issue after the `MSSQL_CLIENT_SECRET` was rotated. This resulted in the same problem. I updated the client secret in the state file (it may occur multiple times). After fixing the client secret in the state file, it all worked again.
> 
> Note that if you store the state in a remote backend (i.e. Azure storage account), then make sure you update the secret in the remote state.

Thanks, you save my day!
