### ISSUE TITLE
String_Split issue

### ISSUE THREAD

**Issue by arouxAgicap** [betr-io/terraform-provider-mssql#31]
I'm currently using version 0.2.4 of the provider and I encounter issues creating multiple users for the same database.
The error message is the following : 
`Error: unable to create user USER: mssql: There is already an object named 'String_Split' in the database`

Looking at the previous issues and PRs, I saw that race condition can occurs if trying to create multiple users & login on the same database and it was supposedly fixed with #24.

Rolling back to 0.2.3 solved the problem

**Comment by alxy** [comment]
May I ask on which compatibility level for the SQL database you are? You can find that out by running `select name, compatibility_level FROM sys.databases` on your database.
