### ISSUE TITLE
Cannot login using only env vars

### ISSUE THREAD

**Issue by rdbartram** [betr-io/terraform-provider-mssql#44]
When trying to create a mssql_user resource using only azure client secrets provided by envvars, i get the error

`on of login,azure_login must be specified`

```terraform
resource "mssql_user" "user" {
  server {
    host = "test.com"
  }

  username = "test"
  roles         = ["db_owner"]
}
```

expected:

read values from envvars, so i dont need to pass them explicitly into the module.

**Comment by alxy** [comment]
You need to at least define the block, but can leave it empty in case you want to source the credentials from environment variables:

```terraform
resource "mssql_login" "example" {
  server {
    host = "example-sql-server.database.windows.net"
    azure_login {}
  }
  login_name = "testlogin"
}
```

**Comment by rdbartram** [comment]
i thought i tried this already and it complained I needed to have then the properties set...it seems to be working now though. thanks
