### ISSUE TITLE
Provide host/username/password in Provider configuration

### ISSUE THREAD

**Issue by stuanderson3** [betr-io/terraform-provider-mssql#5]
It would be great to provide DB host/username/password via the Provider configuration since that information does not change if you're creating multiple users.

**Comment by anderius** [comment]
You for reference: My team creates multiple databases in Terraform, and it is very useful to do that with the same provider setup!

**Comment by DaleyKD** [comment]
I'm sorry to necro this, but is this possible? I don't see any docs about it.
